CREATE DATABASE IF NOT EXISTS date_time;
USE date_time;

SELECT CURRENT_DATE();
SELECT CURRENT_TIME();
SELECT CURRENT_TIMESTAMP();
SELECT DATE(CURRENT_TIMESTAMP());
SELECT TIME(CURRENT_TIMESTAMP());
SELECT YEAR(CURRENT_DATE);
SELECT MONTH(CURRENT_DATE);
SELECT DAY(CURRENT_DATE);
SELECT HOUR(CURRENT_TIME);
SELECT MINUTE(CURRENT_TIME);
SELECT SECOND(CURRENT_TIME);


-- 1) EXTRACT 
SELECT EXTRACT(DAY FROM current_date())  AS "CUURENT_DATE"; 

-- 2) DATEDIFF 
-- SYNTAX
-- SELECT DATEDIFF(date1,date2)

SELECT DATEDIFF('2023-06-05','2022-08-09') AS difference ;


-- 3 ) TIMEDIFF
-- SYNTAX
-- SELECT TIMEDIFF(time1,time2)

SELECT TIMEDIFF(CURRENT_TIMESTAMP(),'2023-08-09 10:12:12') ;

 -- 4 ) DATE_ADD
 -- SYNTAX 
 -- SELECT DATE_ADD(date,INTERVAL value interval_unit);
 
 SELECT DATE_ADD(CURRENT_DATE() ,INTERVAL 1 MONTH);
 
 -- 5) DATE_SUB
 -- SYNTAX 
 -- SELECT DATE_SUB(date, INTERVAL value interval_unit)
 
 
 -- 6) DATE_FORMAT 
 -- SYNTAX
 -- SELECT DATE_FORMAT(date|datetime ,format)
 
 SELECT DATE_FORMAT(CURRENT_DATE(),'%D %b %Y');
 SELECT DATE_FORMAT(CURRENT_TIMESTAMP ,'%h : %i %p');

-- sql date functions

-- GET CURRENT DATE
SELECT CURRENT_DATE;

-- GET CURRENT TIME
SELECT CURRENT_TIMESTAMP;

-- GET CURRENT DATE
SELECT CURRENT_TIME;

-- CONVERT TIMEZONE
SELECT CONVERT_TZ('UTC',CURRENT_TIMESTAMP) AS UTC_TIMEZONE;
SELECT CONVERT_TZ(CURRENT_TIMESTAMP, '+00:00', 'UTC') AS UTC_TIMEZONE;

-- CONVERT DATE TO SUBSEQUENT 4 MONTHS AHEAD
 SELECT MONTH(DATE_ADD(CURRENT_DATE() ,INTERVAL 1 MONTH));
 
 -- 1 MONTHS BACK DATE
  SELECT MONTHNAME(DATE_ADD(CURRENT_DATE() ,INTERVAL -1 MONTH));
  
  -- GET YR FROM DATE
SELECT YEAR(CURRENT_DATE) AS YR_FROM_DATE;

-- GET MTH FROM DATE
SELECT MONTHNAME(CURRENT_DATE) AS MTH_FROM_DATE;

-- GET DAY FROM DATE
SELECT DAY(CURRENT_DATE) AS DAY_FROM_DATE;

-- GET LAST DAY OF current MONTH
SELECT LAST_DAY(CURRENT_DATE) AS last_day_curr_month;

-- GET LAST DAY OF PREVIOUS MONTH
SELECT DAY(LAST_DAY(DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH))) AS LAST_DAY_PREV_MNTH;

SELECT QUARTER(CURRENT_DATE) AS QTR;

SELECT EXTRACT(YEAR FROM CURRENT_DATE) AS YR;
SELECT EXTRACT(MONTH FROM CURRENT_DATE) AS MTH;
SELECT EXTRACT(DAY FROM CURRENT_DATE) AS DAY;

SELECT current_date();

SELECT TO_DATE('1993-08-17') AS DATE;

-- CHANGE CHAR TO DATE FORMAT 
USE flipkart;
SELECT *,STR_TO_DATE(order_date, '%d-%m-%Y') AS "date" -- '%d-%m-%Y' STRING format 
FROM orders;

SELECT DAYNAME('1993-08-23');

SELECT WEEK(CURRENT_DATE); -- FROM 1ST JAN HOW MNAY EEKS HAVE SURPASSED
SELECT MONTH(CURRENT_DATE); -- -- FROM 1ST JAN 2 HOW MNAY MONTHS HAVE SURPASSED

-- 
SELECT NOW();
